# Generated by Django 2.1.5 on 2019-01-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfoId', models.TextField()),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('imageUrl', models.TextField(null=True)),
                ('ip', models.TextField(null=True)),
                ('province', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='UUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField(null=True)),
                ('name', models.CharField(max_length=32)),
                ('amount', models.FloatField(null=True)),
                ('remark', models.CharField(max_length=100)),
                ('relationship', models.TextField(null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('userInfoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Note.User')),
            ],
        ),
    ]
