# Generated by Django 2.1.5 on 2019-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.ImageField(upload_to='img/%y/%m/d'),
        ),
    ]
