# Generated by Django 2.1.5 on 2019-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='end_vip_time',
            field=models.DateTimeField(auto_now=True, verbose_name='vip到期日'),
        ),
    ]
