# Generated by Django 2.1.5 on 2019-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_auto_20190402_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.ImageField(upload_to='img/%y/%m/d'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.ImageField(upload_to='img/%y/%m/d'),
        ),
    ]
