# Generated by Django 2.1.5 on 2019-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0004_auto_20190402_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/food/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.ImageField(upload_to='img/common/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/merchant/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/user/%y%m%d'),
        ),
    ]
