# Generated by Django 2.1.5 on 2019-04-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0005_auto_20190402_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='end_vip_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vip到期日'),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
